pipeline {
    agent any

    parameters{
        text(name:"URL", defaultValue:"https://www.saucedemo.com/", description:"url")
    }

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Test') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'main', url: 'https://github.com/luisaferco/web-automation-pom.git'

                bat(script:'javac src/Main.java', returnStatus: true)
                                    bat "java Main -URL=${params.URL}"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                always{
                    allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: '*/allure-results']]
                    ])
                }
            }
        }
    }
}